- name: Nagios dependecies and libraries Installation
  tags: dependecies, libraries
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php7.4
      - libgd-dev
      - openssl
      - libssl-dev
      - autoconf
      - gcc
      - libc6
      - libmcrypt-dev
      - make
      - libssl-dev
      - wget
      - bc
      - gawk
      - dc
      - build-essential
      - snmp
      - libnet-snmp-perl
      - gettext
      - python3-pip
      - python3
    state: latest

- name: Passslib python package Installation
  pip:
    name: passlib

- name: Making  Directory for downloaded files
  file:
    path: ~/nagios
    state: directory

- name: Nagios download and extract
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Create, Compile and install users and group
  shell: |
    cd ~/nagios/nagioscore-*
    sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
    sudo make all
    sudo make install-groups-users
    sudo usermod -a -G nagios www-data
    sudo make install
    sudo make install-daemoninit
    sudo make install-commandmode
    sudo make install-config
    sudo make install-webconf
    sudo a2enmod rewrite
    sudo a2enmod cgi

- name: Nagios Plugins Download and Extract
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Compilation and Installation
  shell: |
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install

- name: Adding user to a password file and verifying permission are set
  community.general.htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: cordero
    password: lastking23

- name: Verifying the nagios and httpd is starting and enabled
  service:
    name: nagios
    state: restarted
    enabled: true

- name: Verifying the httpd is starting and enabled
  service:
    name: apache2
    state: restarted
    enabled: true

- name: Banner
  debug:
    msg: "Ansible Managed node by Cordero"
  when: ansible_distribution == "Ubuntu"
